<View style={{ width: 375,  height: 24  , }}>    </View> 
<View style={{ width: 120,  height: 16  , }}>    </View> 
<View style={{ width: 12,  height: 9  , }}>    </View> 
<View style={{ width: 12,  height: 3 , backgroundColor: '#fcfcfc' , }}>    </View> 
<View style={{ width: 8,  height: 2 , backgroundColor: '#fcfcfc' , }}>    </View> 
<View style={{ width: 4,  height: 3 , backgroundColor: '#fcfcfc' , }}>    </View> 
<View style={{ width: 33,  height: 5  , }}>    </View> 
<View style={{ width: 5,  height: 5 , backgroundColor: '#fff' , }}>    </View> 
<View style={{ width: 4,  height: 4 , backgroundColor: '#dadada' , }}>    </View> 
<View style={{ width: 5,  height: 5 , backgroundColor: '#dadada' , }}>    </View> 
<View style={{ width: 88,  height: 18  , }}>    </View> 
<View style={{ width: 24,  height: 10  , }}>    </View> 
<View style={{ width: 22,  height: 10 , backgroundColor: '#fff' , }}>    </View> 
<View style={{ width: 21,  height: 8 , backgroundColor: '#dadada' , }}>    </View> 
<View style={{ width: 22,  height: 10 , backgroundColor: '#dadada' , }}>    </View> 
<View style={{ width: 9,  height: 8 , backgroundColor: '#fff' , }}>    </View> 
<View style={{ width: 1,  height: 3 , backgroundColor: '#fff' , }}>    </View> 
<View style={{ width: 5,  height: 10  , }}>    </View> 
<View style={{ width: 375,  height: 60  , }}>    </View> 
<View style={{ width: 24,  height: 24  , }}>    </View> 
<View style={{ width: 18,  height: 12 , backgroundColor: '#000' , }}>    </View> 
<View style={{ width: 18,  height: 2 , backgroundColor: '#dadada' , }}>    </View> 
<View style={{ width: 348,  height: 300  , }}>    </View> 
<View style={{ width: 375,  height: 28  , }}>    </View> 
<View style={{ width: 26,  height: 6  , }}>    </View> 
<View style={{ width: 6,  height: 6 , backgroundColor: '#dadada' , }}>    </View> 
<View style={{ width: 6,  height: 6 , backgroundColor: '#ff473a' , }}>    </View> 
<View style={{ width: 248,  height: 42  , }}>    </View> 
<View style={{ width: 248,  height: 42 , backgroundColor: '#ff473a' , }}>    </View> 
<View style={{ width: 349,  height: 63  , }}>    </View> 
<View style={{ width: 69,  height: 18  , }}>    </View> 
<View style={{ width: 18,  height: 18  , }}>    </View> 
<View style={{ width: 6,  height: 6  , }}>    </View> 
<View style={{ width: 351,  height: 120  , }}>    </View> 
<View style={{ width: 6,  height: 8  , }}>    </View> 
<View style={{ width: 375,  height: 261  , }}>    </View> 
<View style={{ width: 6,  height: 131  , }}>    </View> 
<View style={{ width: 6,  height: 12  , }}>    </View> 
<View style={{ width: 375,  height: 250  , }}>    </View> 
<View style={{ width: 374,  height: 60  , }}>    </View> 
<View style={{ width: 375,  height: 56  , }}>    </View> 
<View style={{ width: 170,  height: 38  , }}>    </View> 
<View style={{ width: 18,  height: 24  , }}>    </View> 
<View style={{ width: 18,  height: 24 , backgroundColor: '#ff473a' , }}>    </View> 
<View style={{ width: 18,  height: 17 , backgroundColor: '#3ec28f' , }}>    </View> 
<View style={{ width: 14,  height: 9 , backgroundColor: '#3ec28f' , }}>    </View> 
<View style={{ width: 4,  height: 4 , backgroundColor: '#fff' , }}>    </View> 
<View style={{ width: 147,  height: 35  , }}>    </View> 
<View style={{ width: 18,  height: 18 , backgroundColor: '#ff473a' , }}>    </View> 
<View style={{ width: 5,  height: 6 , backgroundColor: '#ff473a' , }}>    </View> 
<View style={{ width: 375,  height: 96  , }}>    </View> 
<View style={{ width: 250,  height: 42  , }}>    </View> 
<View style={{ width: 250,  height: 42 , backgroundColor: '#ff473a' , }}>    </View> 
<View style={{ width: 375,  height: 181  , }}>    </View> 
<View style={{ width: 253,  height: 157  , }}>    </View> 
